sudo: required
services:
  - docker

before_install:
  - docker build -t ryanmcalister/docker-react -f dev.Dockerfile .

script:
  - docker run ryanmcalister/docker-react npm run test -- --coverage


